### ISSUE TITLE
Requesting tutorial sometimes returns a "MongoError"

### ISSUE THREAD

**Issue by D0019208** [D0019208/Service-Loop-Server#4]
{"error":true,"response":{"name":"MongoError"}}

**Comment by D0019208** [comment]
Escalating this bug to medium priority. I have found that this error is caused when rapidly requesting a tutorial. The error given by the server is as follows:

MongoError: server is closed
      at executeWriteOperation (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\core\sdam\server.js:470:14)
      at Server.insert (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\core\sdam\server.js:391:5)
      at E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\core\sdam\topology.js:996:15
      at E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\core\sdam\topology.js:452:9
      at selectServers (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\core\sdam\server_selection.js:296:12)
      at NativeTopology.selectServer (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\core\sdam\topology.js:439:5)
      at executeWriteOperation (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\core\sdam\topology.js:964:12)
      at NativeTopology.insert (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\core\sdam\topology.js:600:5)
      at NativeTopology.insert (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\topologies\native_topology.js:58:11)
      at insertDocuments (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\operations\common_functions.js:260:19)
      at InsertOneOperation.execute (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\operations\insert_one.js:26:5)
      at executeOperation (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\operations\execute_operation.js:83:26)
      at Collection.insertOne (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongodb\lib\collection.js:476:10)
      at NativeCollection.<computed> [as insertOne] (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:166:28)
      at model.Model.$__handleSave (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongoose\lib\model.js:266:33)
      at model.Model.$__save (E:\Computing Level 8\DK821 Year 4\Semester 1\Team Project\Code\Service_Loop_Server\node_modules\mongoose\lib\model.js:324:8) {
    name: 'MongoError',
    [Symbol(mongoErrorContextSymbol)]: {}
  }

**Comment by D0019208** [comment]
We have switched to a single connection so this error should be gone, will close issue after YC conducts scalibility test.
